### ISSUE TITLE
Pagination doesn't fire on change event.

### ISSUE THREAD

**Issue by KonradNojman** [thecodejack/svelte-pagination#16]
Hi! I've stumbled upon this issue when trying out your package.

### Code:
I've copied the example from [here](https://github.com/thecodejack/svelte-pagination/blob/master/stories/views/BasicDefaultStyledView.svelte).

### Problem:
Changing of the page doesn't seem to fire `handleChange()` function. When adding `console.log()` inside it's not printing anything. 
It seems like attaching function to e.g. `onChange` doesn't work either.

### Expected behavior
Changing the page either by selecting specific page or pressing `Previous`/`Next` button will fire on change function.

**Comment by thecodejack** [comment]
Hi @KonradNojman 

It is actually svelte event. So change event should be `on:change`. My bad about the examples. I will correct same.
